### ISSUE TITLE
Propose New Logo

### ISSUE THREAD

**Issue by mirzazulfan** [alexmdodge/simply-fast#11]
H @alexmdodge 
I wanted to contribute to your project and I designed a logo for your project. If you like it, you can use it. it's free. I'll send you files and pr, is there anything you want ?
![simplay fast](https://user-images.githubusercontent.com/36124339/39671216-ff1f36aa-513d-11e8-9f63-73ee559c4a96.png)

**Comment by alexmdodge** [comment]
Hi @mirzazulfan! Thank you very much for offering up some logo designs for this project, but I'm not looking to change it at this time. Thank you again for the offer 👍
